### PR TITLE
#160780584 add descriptive readme file 

### PR DESCRIPTION
**Pull request by aayebare**
**What does this PR do?**

- Update the description in README.md
- Remove redundant commented out code in css file
- show the standard commit messages and PR's
- add images to User Interface

**Description of task to be completed?**

- Have a proper description with links to the necessary pages
- Use standard commit messages, PR's and branch names

**How should this be manually tested?**
- Checkout the ft-UI branch to view the application description in the README.md file

**Relevant background context?**

- The description in the README.md file was not well indented.
- The previous PR's and commit messages+ branch names were not standard

**Relevant pivotal tracker stories?**
- #160780584

### CODE REVIEW

**Comment by d-rita** [comment]
Branch name and PR are on point. Commit messages are standard as well. Good work.

**Comment by Sebuliba-Adrian** [comment]
@m-asiimwe  LGTM 👍

**Review by Sebuliba-Adrian — APPROVED** [review]
LGTM

**Comment by kdaglas** [comment]
your commit messages are great... a leaf please

**Pull request merged**
