### PR TITLE
updating User Interface

### PR DESCRIPTION
**Pull request by aayebare**
**What does this PR do?**
-Add a homepage for first time users of the application
-Update the User Interface to include images 
-Links different pages to to allow for authentication of the various users
-Allow for admin and user login

**Description of task to be completed?**
-Have different users login to different homepages as per their roles
-Add a homepage with description of the application
-Add images to the UI to give more context to the application

**How should this be manually tested?**
-Checkout the UI branch to view the application description in the README.md file
-View the User Interface pages at.  https://m-asiimwe.github.io/Fast-Food-Fast/

**Relevant background context?**
-The application has two types of users(admin and customers). They have different roles and rights in the application. This means once they login, they should access different pages

**Relevant pivotal tracker stories?**
-#160780584

**Some Relevant screen shots?**

capture
capture-1
capture-3

### CODE REVIEW

**Comment by Sebuliba-Adrian** [comment]
Please put your PR as in the doc I posted @m-asiimwe

**Comment by billkabanga** [comment]
Nice to see some images in UI. However I have realised that they are kind of clashing with the content forexample the forms. 
For users with visual impairments they might not get the best UX you would want to offer.  Try utilising the `rgba()` css3 style so that you can play around with the opacity using the `alpha`.

**Comment by kdaglas** [comment]
Nice UI sir... this is my added advice maybe make your background darker so that what you truly want the user to see is poping out or unique to the eyes... but this is a nice UI

**Comment by d-rita** [comment]
Good UI. Love how it pops out. Maybe make use of the opacity attribute so that the background does not steal moist of the show.

**Pull request merged**
