### PR TITLE
Adding Doc strings to app and test files

### PR DESCRIPTION
**Pull request by aayebare**
**What does this PR do?**
-Update the README.md file to include documentation
-Commenting the code in api and test files using Doc strings
-Updating message formats for  success and error for endpoint inputs

**Description of task to be completed?**
-Have all code commenting  done using doc strings
-Add a description about the application in the README.md file
-Have a standard message format for success and error

**How should this be manually tested?**
-Checkout the api branch to view the application description in the README.md file
-After cloning the repo, run the command run.py to start up the server
-Use postman to test the end points and view the error and success messages

**Relevant background context?**
-Maintaining an empty list for all orders doesn't allow for some tests to pass in the test_endpoints file, hence the single order in the all_orders list.

**Relevant pivotal tracker stories?**
-#160770155

### CODE REVIEW

**Comment by Sebuliba-Adrian** [comment]
@m-asiimwe Make sure you use the best practices when writing PRs as specified in the guide.

**Review by Sebuliba-Adrian — CHANGES_REQUESTED** [review]
Use the recommended standards as per the guide I posted. The PR format is is not the one specified in the doc.

**Comment by billkabanga** [comment]
Good progress in usage of docstrings. You could also get some time read more about them and understand them better.

**Comment by kdaglas** [comment]
Just as @Sebuliba-Adrian has said... fix that issue and use the recommended standards... leave the hashtags on the title so that you give then that bold nature...

**Comment by billkabanga** [comment]
I don't think you have to take the screenshots of the code for this PR. Because unlike the UI demos/postman actions,  the code that has been modified can be accessed through the commits made. You can always use screenshots when you have to.

**Comment by kdaglas** [comment]
Good coverage...

**Comment by d-rita** [comment]
Good use of docstrings. Good coverage. PR matches the format now.

**Comment by Sebuliba-Adrian** [comment]
@m-asiimwe . Add some neatness to this PR:  **bolden** your headers and add indentation and point bullets. And you branch naming and commit messages should follow the standard.

**Pull request closed without merging**
